### ISSUE TITLE
Directions do not match the spec

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/collections_practice#28]
the directions for bonus collections practice do not match the spec (ex: on learn, question # 3 is sort_array_char_count but the spec is looking for swap_elements) change in the curriculum?

**Comment by AnnJohn** [comment]
@MsUzoAgu  This issue has  a PR that I also assigned to you that might fix it.

**Comment by msuzoagu** [comment]
@AnnJohn: fixed and merged
